ALERT = {
    "PDV_CANCEL": {
        "STOCKOUT": "Muitos pedidos da sua loja estão sendo cancelados com a justificativa de “Falta de Produtos”. Ative no Seu.Zé apenas os itens que você realmente tem em estoque e em quantidade suficiente. Mantenha o estoque SEMPRE atualizado ao longo da operação. Confira a lista de produtos do seu portfólio ideal no Seu.Zé em: 'Estoque de Produtos' > 'Portfólio Ideal.{STOCKOUT_TOP_PRODUCT}",
        "USER CANCELLED": "Muitos pedidos da sua loja estão sendo cancelados com a justificativa de “Cliente Cancelou”. Prepare o seu time para evitar essas situações, ative no Seu.Zé apenas os itens que você realmente tem em estoque e se organize sua equipe de motocas para evitar atrasos.",
        "OUT OF RANGE": "Muitos pedidos da sua loja estão sendo cancelados com a justificativa de “Fora Do Raio”. Prepare o seu time para evitar esses cancelamentos, você consegue ver todas as áreas que fazem parte do seu raio dentro do Seu.Zé em: “Minha Conta” > “Área de Entrega”. Em casos de problemas com áreas de entrega, entre em contato com o seu supervisor.",
        "USER NOT FOUND": "Muitos pedidos da sua loja estão sendo cancelados com a justificativa de “Cliente Não Encontrado”. Prepare o seu time para evitar esses cancelamentos, oriente apenas a cancelar após tentativa de contato.",
        "DUPLICATED ORDER": "Muitos pedidos da sua loja estão sendo cancelados com a justificativa de “Pedido Duplicado”. Prepare o seu time para evitar esses cancelamentos, entre em contato com o cliente para confirmar se esse pedido realmente é duplicado.",
        "RISK AREA": "Muitos pedidos da sua loja estão sendo cancelados com a justificativa de “Área De Risco”. A segurança da equipe é prioridade. Caso tenha uma região de risco dentro do seu raio e que não foi sinalizada ainda, entre em contato com o seu supervisor para ajustar esse ponto.",
        "USER CHANGED ORDER": "Muitos pedidos da sua loja estão sendo cancelados com a justificativa de “Cliente Modificou o Pedido”. Prepare o seu time para evitar esses cancelamentos, ative no Seu.Zé apenas os itens que você realmente tem em estoque e em quantidade suficiente. Mantenha o estoque SEMPRE atualizado ao longo da operação.",
        "DELAYED 3RD COURIER": "Muitos pedidos da sua loja estão sendo cancelados com a justificativa de “Entregador Terceirizado Atrasou”. Prepare o seu time para evitar esses cancelamentos, organize os seus motocas de acordo com a demanda do dia.",
        "OPER ISSUES": "Muitos pedidos da sua loja estão sendo cancelados com a justificativa de “Problemas na Operação”. Prepare o seu time para evitar essas situações, ative no Seu.Zé apenas os itens que você realmente tem em estoque e se organize sua equipe de motocas para evitar atrasos. Você pode entender quais são seus horários de picos com o relatório semanal que te enviamos.",
        "OTHER": "Muitos pedidos da sua loja estão sendo cancelados com a justificativa de “Outros”. Prepare o seu time para evitar essas situações, e peça para serem mais assertivos com os motivos. Caso algum motivo continue se repetindo, entre em contato com o seu supervisor para explicar a situação.",
    },
    "COURIER_CANCEL": {
        "COSTUMER NOT ANSWERED": "Muitos pedidos da sua loja estão sendo cancelados pelo motoca com a justificativa de “Consumidor Não Responde”. Prepare o seu time para evitar esses cancelamentos, oriente o motoca apenas cancelar após tentativa de contato. {FILL_RATE_CANCELED_ON_DELIVERY}% dos pedidos estão sendo cancelados distante da casa do consumidor.",
        "COSTUMER WRONG ADDRESS": "Muitos pedidos da sua loja estão sendo cancelados pelo motoca com a justificativa de “Endereço do Consumidor Errado”. Prepare o seu time para evitar esses cancelamentos, oriente o motoca apenas cancelar após tentativa de contato. {FILL_RATE_CANCELED_ON_DELIVERY}% dos pedidos estão sendo cancelados distante da casa do consumidor.",
        "COSTUMER REFUSED ORDER": "Muitos pedidos da sua loja estão sendo cancelados pelo motoca com a justificativa de “Consumidor Recusou o Pedido”. Prepare o seu time para evitar esses cancelamentos, oriente o motoca a tentar contato e entender o motivo antes de cancelar. {FILL_RATE_CANCELED_ON_DELIVERY}% dos pedidos estão sendo cancelados distante da casa do consumidor.",
        "OTHER": "Muitos pedidos da sua loja estão sendo cancelados pelo motoca com a justificativa de “Outros”. Prepare o seu time para evitar essas situações, e peça para serem mais assertivos com os motivos. Caso algum motivo continue se repetindo, entre em contato com o seu supervisor para explicar a situação. {FILL_RATE_CANCELED_ON_DELIVERY}% dos pedidos estão sendo cancelados distante da casa do consumidor.",
    },
    "USER_CANCEL": {
        "MODIFY ORDER CANCEL": "Muitos pedidos da sua loja estão sendo cancelados pelo usuário por terem sido modificados. Ative no Seu.Zé apenas os itens que você realmente tem em estoque e em quantidade suficiente. Mantenha o estoque SEMPRE atualizado ao longo da operação. Confira a lista de produtos do seu portfólio ideal no Seu.Zé em: 'Estoque de Produtos' > 'Portfólio Ideal'.",
        "LONG ETA": "O usuário está cancelando por alto tempo de espera na liberação do pedido. Avalie colocar mais entregadores. Essa mudança pode trazer mais pedidos para a sua loja.",
        "CANT WAIT": "Muitos pedidos da sua loja estão sendo cancelados pelo usuário com a justificativa de “Não Pode Aguardar”. Prepare o seu time para evitar essas situações, ative no Seu.Zé apenas os itens que você realmente tem em estoque e se organize sua equipe de motocas para evitar atrasos.",
        "LATE ORDER": "Muitos pedidos da sua loja estão sendo cancelados pelo usuário com a justificativa de “Pedido Atrasado”. Prepare o seu time para evitar essas situações, ative no Seu.Zé apenas os itens que você realmente tem em estoque e se organize sua equipe de motocas para evitar atrasos.",
    },
    "PDV_REJECTED": {
        "STOCKOUT": "Muitos pedidos da sua loja estão sendo rejeitados com a justificativa de “Falta de Produtos”. Ative no Seu.Zé apenas os itens que você realmente tem em estoque e em quantidade suficiente. Mantenha o estoque SEMPRE atualizado ao longo da operação. Confira a lista de produtos do seu portfólio ideal no Seu.Zé em: 'Estoque de Produtos' > 'Portfólio Ideal'.",
        "WITHOUT COURIER": "Muitos pedidos da sua loja estão sendo rejeitados com a justificativa de “Sem Entregador”. Organize os seus motocas com o histórico de pedidos da sua loja, você pode entender os são seus horários de picos com o relatório semanal que te enviamos.",
        "SUSPECT OF FRAUD": "Muitos pedidos da sua loja estão sendo rejeitados com a justificativa de “Suspeita de Fraude”. Entre em contato com seu supervisor para ajustar esse ponto",
        "LARGE ORDER": "Muitos pedidos da sua loja estão sendo rejeitados com a justificativa de “Pedido Grande”. Prepare o seu time para evitar esse problema, hoje no Zé temos uma taxa de conveniência para pedidos com mais de 26kg. Evite cancelar pedidos com um peso inferior a esse.",
        "HIGH DEMAND": "Muitos pedidos da sua loja estão sendo rejeitados com a justificativa de “Alta demanda”. Organize os seus motocas com o histórico de pedidos da sua loja, você pode entender os são seus horários de picos com o relatório semanal que te enviamos.",
        "OTHER": "Muitos pedidos da sua loja estão sendo rejeitados com a justificativa de “Outros”. Prepare o seu time para evitar essas situações, e peça para serem mais assertivos com os motivos. Caso algum motivo continue se repetindo, entre em contato com o seu supervisor para explicar a situação.",
        "OPER ISSUES": "Muitos pedidos da sua loja estão sendo rejeitados com a justificativa de “Problemas na Operação”. Prepare o seu time para evitar essas situações, ative no Seu.Zé apenas os itens que você realmente tem em estoque e se organize sua equipe de motocas para evitar atrasos. Você pode entender quais são seus horários de picos com o relatório semanal que te enviamos.",
    },
    "PDV_EXPIRED": "ATENÇÃO: Sua loja está com um alto índice de pedidos expirados. Confira se o áudio do computador está funcionando e feche a loja SEMPRE ao fim do expediente.",
}

CRITICAL = ALERT

NORMAL = {
    "PDV_CANCEL": {
        "STOCKOUT": "Oi Parceiro, alguns pedidos da sua loja estão sendo cancelados com a justificativa de “Falta de Produtos”. Pensando em melhorar cada vez mais sua operação e para não perder pedidos ative no Seu.Zé apenas os itens que você realmente tem em estoque e em quantidade suficiente. Mantenha o estoque SEMPRE atualizado ao longo da operação. Confira a lista de produtos do seu portfólio ideal no Seu.Zé em: 'Estoque de Produtos' > 'Portfólio Ideal.",
        "USER CANCELLED": "Oi Parceiro, alguns pedidos da sua loja estão sendo cancelados com a justificativa de “Cliente Cancelou”. Pensando em melhorar cada vez mais sua operação e para não perder pedidos, prepare o seu time para evitar essas situações, ative no Seu.Zé apenas os itens que você realmente tem em estoque e se organize sua equipe de motocas para evitar atrasos.",
        "OUT OF RANGE": "Oi Parceiro, alguns pedidos da sua loja estão sendo cancelados com a justificativa de “Fora Do Raio”. Pensando em melhorar cada vez mais sua operação e para não perder pedidos, prepare o seu time para evitar esses cancelamentos, você consegue ver todas as áreas que fazem parte do seu raio dentro do Seu.Zé em: “Minha Conta” > “Área de Entrega”. Em casos de problemas com áreas de entrega, entre em contato com o seu supervisor.",
        "USER NOT FOUND": "Oi Parceiro, alguns pedidos da sua loja estão sendo cancelados com a justificativa de “Cliente Não Encontrado”. Pensando em melhorar cada vez mais sua operação e para não perder pedidos, prepare o seu time para evitar esses cancelamentos, oriente apenas a cancelar após tentativa de contato.",
        "DUPLICATED ORDER": "Oi Parceiro, alguns pedidos da sua loja estão sendo cancelados com a justificativa de “Pedido Duplicado”. Pensando em melhorar cada vez mais sua operação e para não perder pedidos, prepare o seu time para evitar esses cancelamentos, entre em contato com o cliente para confirmar se esse pedido realmente é duplicado.",
        "RISK AREA": "Oi Parceiro, alguns pedidos da sua loja estão sendo cancelados com a justificativa de “Área De Risco”. A segurança da equipe é prioridade. Pensando em melhorar cada vez mais sua operação e para não perder pedidos, caso tenha uma região de risco dentro do seu raio e que não foi sinalizada ainda, entre em contato com o seu supervisor para ajustar esse ponto.",
        "USER CHANGED ORDER": "Oi Parceiro, alguns pedidos da sua loja estão sendo cancelados com a justificativa de “Cliente Modificou o Pedido”. Pensando em melhorar cada vez mais sua operação e para não perder pedidos, prepare o seu time para evitar esses cancelamentos, ative no Seu.Zé apenas os itens que você realmente tem em estoque e em quantidade suficiente. Mantenha o estoque SEMPRE atualizado ao longo da operação.",
        "DELAYED 3RD COURIER": "Oi Parceiro, alguns pedidos da sua loja estão sendo cancelados com a justificativa de “Entregador Terceirizado Atrasou”. Pensando em melhorar cada vez mais sua operação e para não perder pedidos, prepare o seu time para evitar esses cancelamentos, organize os seus motocas de acordo com a demanda do dia.",
        "OPER ISSUES": "Oi Parceiro, alguns pedidos da sua loja estão sendo cancelados com a justificativa de “Problemas na Operação”. Pensando em melhorar cada vez mais sua operação e para não perder pedidos, prepare o seu time para evitar essas situações, ative no Seu.Zé apenas os itens que você realmente tem em estoque e se organize sua equipe de motocas para evitar atrasos. Você pode entender quais são seus horários de picos com o relatório semanal que te enviamos.",
        "OTHER": "Oi Parceiro, alguns pedidos da sua loja estão sendo cancelados com a justificativa de “Outros”. Pensando em melhorar cada vez mais sua operação e para não perder pedidos, prepare o seu time para evitar essas situações, e peça para serem mais assertivos com os motivos. Caso algum motivo continue se repetindo, entre em contato com o seu supervisor para explicar a situação.",
    },
    "COURIER_CANCEL": {
        "COSTUMER NOT ANSWERED": "Oi Parceiro, alguns pedidos da sua loja estão sendo cancelados pelo motoca com a justificativa de “Consumidor Não Responde”. Pensando em melhorar cada vez mais sua operação e para não perder pedidos, prepare o seu time para evitar esses cancelamentos, oriente o motoca apenas cancelar após tentativa de contato. {FILL_RATE_CANCELED_ON_DELIVERY}% dos pedidos estão sendo cancelados distante da casa do consumidor.",
        "COSTUMER WRONG ADDRESS": " Oi Parceiro, alguns pedidos da sua loja estão sendo cancelados pelo motoca com a justificativa de “Endereço do Consumidor Errado”. Pensando em melhorar cada vez mais sua operação e para não perder pedidos, prepare o seu time para evitar esses cancelamentos, oriente o motoca apenas cancelar após tentativa de contato. {FILL_RATE_CANCELED_ON_DELIVERY}% dos pedidos estão sendo cancelados distante da casa do consumidor.",
        "COSTUMER REFUSED ORDER": " Oi Parceiro, alguns pedidos da sua loja estão sendo cancelados pelo motoca com a justificativa de “Consumidor Recusou o Pedido”. Pensando em melhorar cada vez mais sua operação e para não perder pedidos, prepare o seu time para evitar esses cancelamentos, oriente o motoca a tentar contato e entender o motivo antes de cancelar. {FILL_RATE_CANCELED_ON_DELIVERY}% dos pedidos estão sendo cancelados distante da casa do consumidor.",
        "OTHER": " Oi Parceiro, alguns pedidos da sua loja estão sendo cancelados pelo motoca com a justificativa de “Outros”. Pensando em melhorar cada vez mais sua operação e para não perder pedidos, prepare o seu time para evitar essas situações, e peça para serem mais assertivos com os motivos. Caso algum motivo continue se repetindo, entre em contato com o seu supervisor para explicar a situação. {FILL_RATE_CANCELED_ON_DELIVERY}% dos pedidos estão sendo cancelados distante da casa do consumidor.",
    },
    "USER_CANCEL": {
        "MODIFY ORDER CANCEL": "Oi Parceiro, alguns pedidos da sua loja estão sendo cancelados pelo usuário por terem sido modificados. Pensando em melhorar cada vez mais sua operação e para não perder pedidos, ative no Seu.Zé apenas os itens que você realmente tem em estoque e em quantidade suficiente. Mantenha o estoque SEMPRE atualizado ao longo da operação. Confira a lista de produtos do seu portfólio ideal no Seu.Zé em: 'Estoque de Produtos' > 'Portfólio Ideal'.",
        "LONG ETA": "Oi Parceiro, o usuário está cancelando por alto tempo de espera na liberação do pedido. Pensando em melhorar cada vez mais sua operação e para não perder pedidos, avalie colocar mais entregadores. Essa mudança pode trazer mais pedidos para a sua loja.",
        "CANT WAIT": "Oi Parceiro, alguns pedidos da sua loja estão sendo cancelados pelo usuário com a justificativa de “Não Pode Aguardar”. Pensando em melhorar cada vez mais sua operação e para não perder pedidos, prepare o seu time para evitar essas situações, ative no Seu.Zé apenas os itens que você realmente tem em estoque e se organize sua equipe de motocas para evitar atrasos.",
        "LATE ORDER": "Oi Parceiro, alguns pedidos da sua loja estão sendo cancelados pelo usuário com a justificativa de “Pedido Atrasado”. Pensando em melhorar cada vez mais sua operação e para não perder pedidos, prepare o seu time para evitar essas situações, ative no Seu.Zé apenas os itens que você realmente tem em estoque e se organize sua equipe de motocas para evitar atrasos.",
    },
    "PDV_REJECTED": {
        "STOCKOUT": "Oi Parceiro, alguns pedidos da sua loja estão sendo rejeitados com a justificativa de “Falta de Produtos”. Pensando em melhorar cada vez mais sua operação e para não perder pedidos, ative no Seu.Zé apenas os itens que você realmente tem em estoque e em quantidade suficiente. Mantenha o estoque SEMPRE atualizado ao longo da operação. Confira a lista de produtos do seu portfólio ideal no Seu.Zé em: 'Estoque de Produtos' > 'Portfólio Ideal'.",
        "WITHOUT COURIER": "Oi Parceiro, alguns pedidos da sua loja estão sendo rejeitados com a justificativa de “Sem Entregador”. Pensando em melhorar cada vez mais sua operação e para não perder pedidos, organize os seus motocas com o histórico de pedidos da sua loja, você pode entender os são seus horários de picos com o relatório semanal que te enviamos.",
        "SUSPECT OF FRAUD": "Oi Parceiro, alguns pedidos da sua loja estão sendo rejeitados com a justificativa de “Suspeita de Fraude”. Pensando em melhorar cada vez mais sua operação, entre em contato com seu supervisor para ajustar esse ponto",
        "LARGE ORDER": "Oi Parceiro, alguns pedidos da sua loja estão sendo rejeitados com a justificativa de “Pedido Grande”. Pensando em melhorar cada vez mais sua operação, hoje no Zé temos uma taxa de conveniência para pedidos com mais de 26kg. Evite cancelar pedidos com um peso inferior a esse.",
        "HIGH DEMAND": "Oi Parceiro, alguns pedidos da sua loja estão sendo rejeitados com a justificativa de “Alta demanda”. Pensando em melhorar cada vez mais sua operação e para não perder pedidos, organize os seus motocas com o histórico de pedidos da sua loja, você pode entender os são seus horários de picos com o relatório semanal que te enviamos.",
        "OTHER": "Oi Parceiro, alguns pedidos da sua loja estão sendo rejeitados com a justificativa de “Outros”. Pensando em melhorar cada vez mais sua operação e para não perder pedidos, prepare o seu time para evitar essas situações, e peça para serem mais assertivos com os motivos. Caso algum motivo continue se repetindo, entre em contato com o seu supervisor para explicar a situação.",
        "OPER ISSUES": "Oi Parceiro, alguns pedidos da sua loja estão sendo rejeitados com a justificativa de “Problemas na Operação”. Pensando em melhorar cada vez mais sua operação e para não perder pedidos, prepare o seu time para evitar essas situações, ative no Seu.Zé apenas os itens que você realmente tem em estoque e se organize sua equipe de motocas para evitar atrasos. Você pode entender quais são seus horários de picos com o relatório semanal que te enviamos",
    },
    "PDV_EXPIRED": "ATENÇÃO: Oi Parceiro, sua loja está com um alto índice de pedidos expirados. Pensando em melhorar cada vez mais sua operação e para não perder pedidos, confira se o áudio do computador está funcionando e feche a loja SEMPRE ao fim do expediente.",
}

CONGRATS = "Olá, parceiro. Sua taxa de aceitação de pedidos está superior a 94%, nível adequado que demonstra o empenho em oferecer um ótimo serviço. Seu resultado semanal foi de {FILL_RATE_INDEX} Continue seguindo as boas práticas de atendimento e evitando cancelamentos. Se tiver alguma dificuldade em concluir pedidos, entre em contato para encontrarmos uma solução juntos!"

HEADER = {
    "ALERT": "⚠️ *ALTO ÍNDICE DE CANCELAMENTO DE PEDIDOS* ⚠️",
    "CRITICAL": "⚠️ *ALTO ÍNDICE DE CANCELAMENTO DE PEDIDOS* ⚠️",
    "NORMAL": "*ÍNDICE DE CANCELAMENTO DE PEDIDOS*",
    "CONGRATS": "🎉 *PARABÉNS* 🎉",
}
